#!/usr/bin/env python3
"""Convert the government hospital directory CSV into database/seed_hospitals_govt.sql.

Usage (from the project root):
    python tools/import_hospitals.py

Reads  database/data/Hospital_with_discipline_jul_15.csv  (Windows-1252 encoded)
Writes database/seed_hospitals_govt.sql
Nothing is invented: every value comes from the CSV; 'NA'/blank become NULL.
"""
import csv, re, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "database", "data", "Hospital_with_discipline_jul_15.csv")
OUT = os.path.join(ROOT, "database", "seed_hospitals_govt.sql")

def clean(v):
    if v is None: return None
    v = re.sub(r"\s+", " ", v.replace("\x96", "-")).strip()
    return None if v == "" or v.upper() == "NA" else v

def sql(v, maxlen=None):
    if v is None: return "NULL"
    if maxlen: v = v[:maxlen]
    return "'" + v.replace("\\", "\\\\").replace("'", "''") + "'"

def phone_of(contact):
    if not contact: return None
    m = re.search(r"(?i)phone\s*[-:]?\s*(.*)$", contact)
    return m.group(1).strip(" .,") if m else None

rows = []
with open(SRC, newline="", encoding="cp1252") as f:
    for r in csv.DictReader(f):
        name = clean(r["Hospital / Private"])
        if not name: continue
        name = name.rstrip(" ,")
        cat = clean(r["Category"])
        cat = cat.capitalize() if cat else None
        pin = clean(r["Area Pin Code"])
        pin = re.sub(r"\D", "", pin)[:6] if pin else None
        contact = clean(r["Contact Details"])
        rows.append((name, clean(r["State"]), clean(r["City"]), cat,
                     clean(r["Systems of Medicine"]), pin, contact, phone_of(contact),
                     clean(r["Email address"]), clean(r["Website link"]),
                     clean(r["Specializations"]), clean(r["Services"])))

cols = ("name,state,city,location,category,system_of_medicine,pin_code,"
        "contact_details,phone,email,website,specializations,services")
with open(OUT, "w", encoding="utf-8", newline="\n") as o:
    o.write("-- Generated by tools/import_hospitals.py from the government hospital directory\n"
            "-- (Hospital_with_discipline_jul_15.csv). %d facilities. Run after schema.sql.\n"
            "USE medipriority;\nSET NAMES utf8mb4;\n\n" % len(rows))
    for i in range(0, len(rows), 100):
        o.write(f"INSERT INTO hospitals ({cols}) VALUES\n")
        vals = []
        for (name, st, city, cat, sysm, pin, contact, ph, em, web, spec, svc) in rows[i:i+100]:
            loc = ", ".join(x for x in (city, st) if x)
            vals.append("(" + ", ".join([sql(name,200), sql(st,60), sql(city,80), sql(loc,150),
                sql(cat,10), sql(sysm,120), sql(pin,6), sql(contact), sql(ph,255),
                sql(em,255), sql(web,255), sql(spec), sql(svc)]) + ")")
        o.write(",\n".join(vals) + ";\n\n")
print("wrote", OUT, len(rows), "rows")
